### ISSUE TITLE
New OP template loads logo from GH

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#7]
If the file is deleted, moved, or anything happens to the repo or GH links, the published specs won't render:

```html
<a href="https://www.oasis-open.org/"><img width="50%" src="https://github.com/oasis-open-projects/documentation/raw/master/img/open-project-logos/open-projects-logo.jpeg.jpg" alt="OASIS Open Projects" border="0" /></a>
```

**Comment by jamsden** [comment]
I thought the published specs were rendered as HTML and all their links are either relative or to other published specs.

**Comment by paul-knight** [comment]
In order to ensure a more permanent and reliable source for the OASIS OP logo, the logo file is available as either .jpg or .png at the following locations:
- https://docs.oasis-open-projects.org/templates/logo/open-projects-logo.jpg
- https://docs.oasis-open-projects.org/templates/logo/open-projects-logo.png

These logo files have been cropped to remove extra white space and allow them to be aligned left-justified.

**Comment by berezovskyi** [comment]
Thanks! It will go into the RM PSD, our next draft to be published.

--
/Andrew
(from phone)

5 sep. 2019 kl. 22:16 skrev Paul Knight <notifications@github.com<mailto:notifications@github.com>>:


In order to ensure a more permanent and reliable source for the OASIS OP logo, the logo file is available as either .jpg or .png at the following locations:

  *   https://docs.oasis-open-projects.org/templates/logo/open-projects-logo.jpg
  *   https://docs.oasis-open-projects.org/templates/logo/open-projects-logo.png

These logo files have been cropped to remove extra white space and allow them to be aligned left-justified.
