### ISSUE TITLE
ReSpec still warns about conformance table with noConformanceTable set

### ISSUE THREAD

**Issue by berezovskyi** [oasis-tcs/tab-respec#8]
After [setting 'noConformanceTable' to true](https://github.com/oslc-op/oslc-specs/pull/103/commits/66828a6348ff55e177086c962284e63ff7d87fca), the warning still appears:

> A conformance paragraph or table is required for your type of document.

**Comment by ndjc** [comment]
I realized that the setting 'noConformanceTable' was not in fact intended to suppress the warning. The idea was that all standards track documents need a conformance paragraph of some form - it can be the generated conformance table full of clauses marked with the conformance style, or it can be one or more paragraphs of custom text, or both. The custom text could say something like "To be conformant with this specification, a server MUST use RDF terms and shapes that are compliant with this document. A server MAY define additional terms and shapes."

The 'noConformanceTable' flag was to indicate that a spec document wanted to use its custom text and **only** that custom text, and not to include a table of the conformance clauses.

I can introduce a new setting to suppress the entire conformance checking, so that a standards track document need not have any clauses or paragraphs, **if** we think that's what we want.

**Comment by berezovskyi** [comment]
- [ ] @berezovskyi to set the https://open-services.net/spec/cm/latest and https://open-services.net/spec/cm/latest-draft redirects properly

**Comment by ndjc** [comment]
I'm not sure if the thumbs-up in the previous comment was a vote to add a new suppression setting? Is a document with no conformance table going to be acceptable to OASIS?

**Comment by berezovskyi** [comment]
Yes it was! I think yes, vocab parts don’t require it. Jim?

--
/Andrew
(from phone)

13 aug. 2019 kl. 21:58 skrev Nick Crossley <notifications@github.com<mailto:notifications@github.com>>:


I'm not sure if the thumbs-up in the previous comment was a vote to add a new suppression setting? Is a document with no conformance table going to be acceptable to OASIS?

**Comment by jamsden** [comment]
I don't mind the warning. Its a good reminder.

**Comment by berezovskyi** [comment]
Thanks everyone. @ndjc please disregard.
